export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';

export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';

export const INVALIDATE_STORE = 'INVALIDATE_STORE';

export const LOAD_SCHEMA_DEF_LIST_SUCCESS = 'LOAD_SCHEMA_DEF_LIST_SUCCESS';
export const LOAD_SCHEMA_DEF_LIST_FAILURE = 'LOAD_SCHEMA_DEF_LIST_FAILURE';

export const LOAD_SCHEMA_DEF_SUCCESS = 'LOAD_SCHEMA_DEF_SUCCESS';
export const LOAD_SCHEMA_DEF_FAILURE = 'LOAD_SCHEMA_DEF_FAILURE';

export const DELETE_SCHEMA_DEF_SUCCESS = 'DELETE_SCHEMA_DEF_SUCCESS';
export const DELETE_SCHEMA_DEF_FAILURE = 'DELETE_SCHEMA_DEF_FAILURE';

export const TASK_LIST_SUCCESS = 'TASK_LIST_SUCCESS';

export const TABLE_DEF_LOAD_SUCCESS = 'TABLE_DEF_LOAD_SUCCESS';
