export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';

export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';

export const INVALIDATE_STORE = 'INVALIDATE_STORE';

export const SCHEMA_DEF_LIST_SUCCESS = 'SCHEMA_DEF_LIST_SUCCESS';

export const TASK_LIST_SUCCESS = 'TASK_LIST_SUCCESS';

export const TABLE_DEF_LOAD_SUCCESS = 'TABLE_DEF_LOAD_SUCCESS';
