export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';

export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';

export const INVALIDATE_STORE = 'INVALIDATE_STORE';

export const TASK_LIST_SUCCESS = 'TASK_LIST_SUCCESS';


/**
 * SchemaDef Actions
 */

//* Read *******
// Full Data
export const SCHEMA_DEF_FULL_LOAD_SUCCESS = 'SCHEMA_DEF_FULL_LOAD_SUCCESS';
export const SCHEMA_DEF_FULL_LOAD_FAILURE = 'SCHEMA_DEF_FULL_LOAD_FAILURE';

// Read List
export const SCHEMA_DEF_LIST_LOAD_SUCCESS = 'SCHEMA_DEF_LIST_LOAD_SUCCESS';
export const SCHEMA_DEF_LIST_LOAD_FAILURE = 'SCHEMA_DEF_LIST_LOAD_FAILURE';

// Delete
export const SCHEMA_DEF_DELETE_SUCCESS = 'SCHEMA_DEF_DELETE_SUCCESS';
export const SCHEMA_DEF_DELETE_FAILURE = 'SCHEMA_DEF_DELETE_FAILURE';


/**
 * TableDef Actions
 */

//* Create *******
// Read Base Data
export const TABLE_DEF_CREATE_SUCCESS = 'TABLE_DEF_CREATE_SUCCESS';
export const TABLE_DEF_CREATE_FAILURE = 'TABLE_DEF_CREATE_FAILURE';
